# -*- coding: utf-8 -*-
"""App_Syifa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p07ybQjHsOFWoqgMK6v6g_PTvjUWnIQp
"""

#pip install streamlit
#pip install ultralytics

import streamlit as st
import time
from PIL import Image
from ultralytics import YOLO
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image
import cv2

# === Load Models ===
@st.cache_resource
def load_models():
    yolo_model = YOLO("Model/best.pt")  # Model deteksi objek
    classifier = tf.keras.models.load_model("Model/Syifa Salsabila_Laporan 2.h5")  # Model klasifikasi
    return yolo_model, classifier

yolo_model, classifier = load_models()

# === KONFIGURASI DASAR ===
st.set_page_config(page_title="Ursidetect", page_icon="🐻", layout="centered")

# === STATE MANAGEMENT ===
if "step" not in st.session_state:
    st.session_state.step = 1
if "name" not in st.session_state:
    st.session_state.name = ""

# === NAVIGATION BAR (Progress Bar Sederhana) ===
def progress_bar(step):
    steps = ["Welcome to Ursidetect", "About Ursidetect", "Enter Your Name", "Let's Start"]
    cols = st.columns(len(steps))
    for i, label in enumerate(steps):
        with cols[i]:
            if i + 1 == step:
                st.markdown(f"**<span style='color:#2563eb;'>{i+1}. {label}</span>**", unsafe_allow_html=True)
            else:
                st.markdown(f"<span style='color:gray;'>{i+1}. {label}</span>", unsafe_allow_html=True)

# === STEP 1 ===
if st.session_state.step == 1:
    progress_bar(1)
    st.image("https://images.unsplash.com/photo-1640622653142-4e8c184a99b1", use_container_width=True)
    st.title("Welcome to Ursidetect")
    st.write("Your intelligent image analysis companion powered by advanced AI technology.")
    st.write("Discover what's in your images with precision and ease.")
    if st.button("Get Started"):
        st.session_state.step = 2
        st.rerun()
    # === STEP 2 ===
elif st.session_state.step == 2:
    progress_bar(2)
    st.image("https://images.unsplash.com/photo-1625580916819-6efb3a3f26f7", use_container_width=True)
    st.title("About Ursidetect")
    st.markdown("""
    **Ursidetect** is an advanced AI-powered image analysis platform that offers two powerful features:
    - 🔍 **Object Detection:** Identify and locate multiple objects within your images with bounding boxes.
    - 🖼️ **Image Classification:** Classify your entire image into specific categories with confidence scores.

    Simply upload your image, choose your preferred analysis method, and let our AI do the rest!
    """)
    if st.button("Continue"):
        st.session_state.step = 3
        st.rerun()
      # === STEP 3 ===
elif st.session_state.step == 3:
    progress_bar(3)
    st.image("https://cdn.dribbble.com/users/1162077/screenshots/3848914/programmer.gif", width=400)
    st.title("What's Your Name?")
    st.write("Let's personalize your experience with Ursidetect.")
    name_input = st.text_input("Enter your name:")
    if st.button("Continue") and name_input.strip() != "":
        st.session_state.name = name_input.strip()
        st.session_state.step = 4
        st.rerun()
    # === STEP 4 ===
elif st.session_state.step == 4:
    progress_bar(4)
    st.title(f"hello, {st.session_state.name.lower().split()[0]}! 👋")
    st.caption("readyToStart")

    col1, col2 = st.columns([1, 1])

    # === KIRI: UPLOAD & PILIH TIPE ANALISIS ===
    with col1:
        st.subheader("uploadImage")
        uploaded_file = st.file_uploader("", type=["jpg", "jpeg", "png"], label_visibility="collapsed")

        if uploaded_file:
            image = Image.open(uploaded_file)
            st.image(image, caption=uploaded_file.name, use_container_width=True)
        else:
            st.info("Upload an image first.")

        st.write("selectAnalysisType")
        analysis_type = st.radio(
            "",
            ["objectDetection", "imageClassification"],
            captions=["objectDetectionDesc", "imageClassificationDesc"],
        )

        analyze_button = st.button("analyze", use_container_width=True)

    # === KANAN: HASIL ===
    with col2:
        st.subheader("results")

        if analyze_button:
            if not uploaded_file:
                st.warning("Please upload an image before analyzing.")
            else:
                # Simulasi proses analisis
                with st.spinner("processing\npleaseWait"):
                    time.sleep(2)

                # === Dummy hasil simulasi ===
                if analysis_type == "objectDetection":
                    st.write("**objectDetection**")
                    st.write("Person — 95%")
                    st.write("Car — 87%")
                    st.write("Tree — 76%")
                else:
                    st.write("**imageClassification**")
                    st.write("Certificate — 98%")

                # === FEEDBACK BOX ===
                st.markdown("---")
                st.subheader("💬 Feedback")
                feedback_text = st.text_area("How was your experience?", placeholder="Share your thoughts here...")
                if st.button("Submit Feedback"):
                    if feedback_text.strip() == "":
                        st.warning("Please write some feedback before submitting.")
                    else:
                        st.success("✅ Thank you for your feedback!")

    # === RESTART BUTTON ===
    st.markdown("---")
    if st.button("🔁 Restart"):
        st.session_state.step = 1
        st.session_state.name = ""
        st.rerun()
