# -*- coding: utf-8 -*-
"""App_Syifa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p07ybQjHsOFWoqgMK6v6g_PTvjUWnIQp
"""

#pip install streamlit
#pip install ultralytics

# === Import Library ===
import streamlit as st
import time
from PIL import Image
from ultralytics import YOLO
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image
import cv2

# === LOAD MODELS ===
@st.cache_resource
def load_models():
    yolo_model = YOLO("Model/best.pt")  # Model deteksi Gambar
    classifier = tf.keras.models.load_model("Model/Syifa Salsabila_Laporan 2.h5")  # Model klasifikasi
    return yolo_model, classifier

yolo_model, classifier = load_models()

# === KONFIGURASI DASAR HALAMAN WEB ===
st.set_page_config(page_title="Ursidetect", page_icon="🐻🐼", layout="centered")

# === STATE MANAGEMENT ===
if "step" not in st.session_state:
    st.session_state.step = 1
if "name" not in st.session_state:
    st.session_state.name = ""

# === NAVIGATION BAR (Progress Bar Sederhana) ===
def progress_bar(step):
    steps = ["Welcome to Ursidetect", "About Ursidetect", "Enter Your Name", "Let's Start"]
    cols = st.columns(len(steps))
    for i, label in enumerate(steps):
        with cols[i]:
            if i + 1 == step:
                st.markdown(f"**<span style='color:#2563eb;'>{i+1}. {label}</span>**", unsafe_allow_html=True)
            else:
                st.markdown(f"<span style='color:gray;'>{i+1}. {label}</span>", unsafe_allow_html=True)

# === STEP 1 ===
if st.session_state.step == 1:
    st.image("slide 1.jpg", use_container_width=True)
    st.title("Tentang Ursidetect")
    st.markdown("""
    Selamat datang di **Ursidetect** 
    st.write("""
    Sebelum kita mulai berpetualang, kenalan dulu yuk dengan Ursidetect!
    Ursidetect adalah platform berbasis kecerdasan buatan (AI) yang dapat mendeteksi dan mengklasifikasikan hewan panda dan beruang.
    """)
    
    col1, col2 = st.columns(2)
    with col1:
        st.markdown(
        """
    <div style="
        background-color:#E6F0FF;
        padding:20px;
        border-radius:15px;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        text-align:center;">
        <h4>🔎 Deteksi Gambar</h4>
        <p style="color:#333;">
        Ursidetect dapat menemukan dan menandai posisi panda atau beruang di dalam gambar 
        menggunakan <b>kotak pembatas (bounding box)</b>.
        </p>
    </div>
    """, 
        unsafe_allow_html=True)
        
    with col2:
        st.markdown(
        """
    <div style="
        background-color:#FFF7E6;
        padding:20px;
        border-radius:15px;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        text-align:center;">
        <h4>🐼 Klasifikasi Gambar</h4>
        <p style="color:#333;">
        Ursidetect mampu menentukan apakah gambar tersebut termasuk <b>panda</b> 
        atau <b>beruang</b>, lengkap dengan tingkat kepercayaan (confidence score).
        </p>
    </div>
    """, 
        unsafe_allow_html=True)
        
    st.markdown("""
    ---
    Kalau sudah penasaran, yuk lanjut ke langkah berikutnya untuk mulai menjelajah!
    """)

    col_kiri, col_kanan = st.columns([4, 1])
    with col_kanan:
        if st.button("Lanjutkan 🐾"):
            st.session_state.step = 2
            st.rerun()

# === STEP 2 ===
elif st.session_state.step == 2:
    st.image("slide 3-1.png", width=300)
    st.write("Sekarang giliran kamu! Masukkan namamu supaya Ursidetect tahu siapa partner barunya 🐾")

    name_input = st.text_input("", placeholder="Contoh: Ursi")
    col_kiri, col_kanan = st.columns([4, 1])
    with col_kanan:
        if st.button("Lanjutkan 🐾"):
            if name_input.strip() != "":
                st.session_state.name = name_input.strip()
                st.session_state.step = 3
                st.rerun()
            else:
                st.info("Ups, sepertinya kamu lupa menulis namamu dulu nih 😊")

# === STEP 3 ===
elif st.session_state.step == 3:
    st.title(f"Hai, {st.session_state.name.lower().split()[0]}! 👋")
    st.caption("Selamat datang di markas petualangan Ursidetect!")
    st.caption("Pilih mode favoritmu: mau jadi pemburu hewan (deteksi) atau peneliti hewan (klasifikasi)?")

    analysis_type = st.radio(
        "Pilih Mode Petualang:",
        ["Pemburu Hewan (Deteksi)", "Peneliti Hewan (Klasifikasi)"],
        horizontal=True,
        index=0)
    st.divider()

    st.markdown("### Masukkan Gambar")
    st.caption(f"Untuk mulai berpetualang, {st.session_state.name.lower().split()[0]} harus memasukkan gambar berbentuk jpg, jpeg atau png yaa.")
    uploaded_file = st.file_uploader("Pilih gambar (jpg, jpeg, png):", type=["jpg", "jpeg", "png"])
    
    if uploaded_file:
        image = Image.open(uploaded_file)
        st.image(image, caption=uploaded_file.name, use_container_width=True)
        st.info("Hebat! Sekarang klik Mulai Petualangan untuk mengenali makhluk lucu dalam gambar kamu!")
    
    st.divider()
    st.markdown("### Hasil Petualangan")
    analyze_button = st.button("🔎 Mulai Petualangan", use_container_width=True)

    if analyze_button:
        if not uploaded_file:
            st.warning("⚠️ Silakan masukkan gambar terlebih dahulu sebelum berpetualang.")
        else:
            with st.spinner("⏳ Sedang Berpetualang..."):
                time.sleep(2)
            st.success("🎉 Hasil analisis muncul di sini!")

            # ... (kode hasil deteksi/klasifikasi di sini)
    
    col_kiri, col_kanan = st.columns([4, 1])
    with col_kanan:
    if st.button("Lanjutkan 🐾"):
        st.session_state.step = 4
        st.rerun()

# === STEP 4 ===
elif st.session_state.step == 4:
    st.subheader("💬 Cerita Petualanganmu")
    st.info("""
    Petualanganmu bersama Ursidetect sudah selesai 🐾  
    Ceritakan pengalamanmu, ya! Kami ingin tahu bagaimana rasanya menjelajahi dunia panda & beruang bersama AI ini.
    """)
    feedback_text = st.text_area("Bagaimana Petualanganmu?", placeholder="Kirimkan ceritamu di sini...")

    if st.button("Kirim Cerita Petualanganku"):
        if feedback_text.strip() == "":
            st.warning("Cerita Anda sangat berarti bagi kami 😊")
        else:
            st.success(f"✅ Terima kasih atas ceritanya, {st.session_state.name.lower().split()[0]}!")

    st.markdown("---")
    if st.button("🔁 Mau memulai lagi?"):
        st.session_state.step = 1
        st.session_state.name = ""
        st.rerun()
